version: '3.2'

services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mymysql'
    ports:
      - '33006:3306'
    volumes:
      - '~/mnt/mysql/:/var/lib/mysql/'
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=stc
#  redis:
#    image: 'redis:latest'
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - '6379:6379'
